DESIGN_NAME: macro_sand_array
VERILOG_FILES:
- src/sand_cell_forMacro.sv
- src/sand_array_forMacro.sv
- src/macro_sand_array_Complex.sv
# - dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_2P_1024x16_c2_bm_bist.v
# - dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_2P_core_behavioral_bm_bist_ideal.v

USE_SLANG: true

# 30% because the design is too small.
FP_CORE_UTIL: 30

FP_ASPECT_RATIO: 1.0
PL_TARGET_DENSITY: 0.55 

# MACROS:
#   "RM_IHPSG13_2P_1024x16_c2_bm_bist":
#     gds: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/gds/RM_IHPSG13_2P_1024x16_c2_bm_bist.gds
#     lef: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/lef/RM_IHPSG13_2P_1024x16_c2_bm_bist.lef
#     lib: 
#       nom_typ_1p20V_25C: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_typ_1p20V_25C.lib
#       nom_fast_1p32V_m40C: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_fast_1p32V_m55C.lib
#       nom_slow_1p08V_125C: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_slow_1p08V_125C.lib

