DESIGN_NAME: macro_sand_array
VERILOG_FILES:
- src/sand_cell_forMacro.sv
- src/sand_array_forMacro.sv
- src/macro_sand_array.sv
- src/sand_grid_RAM.sv
- src/ram_FPGA_2P.sv
- dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_2P_1024x16_c2_bm_bist.v
- dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_2P_core_behavioral_bm_bist_ideal.v

USE_SLANG: true

# 30% because the design is too small.
FP_CORE_UTIL: 30

FP_ASPECT_RATIO: 1.0
PL_TARGET_DENSITY: 0.55 

# use ASIC version of RAM
SYNTH_DEFINES:
  - RAM_ASIC

MACROS:
  "RM_IHPSG13_2P_1024x16_c2_bm_bist":
    gds: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/gds/RM_IHPSG13_2P_1024x16_c2_bm_bist.gds
    lef: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/lef/RM_IHPSG13_2P_1024x16_c2_bm_bist.lef
    lib: 
      nom_typ_1p20V_25C: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_typ_1p20V_25C.lib
      nom_fast_1p32V_m40C: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_fast_1p32V_m55C.lib
      nom_slow_1p08V_125C: dir::../../../pdk/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_slow_1p08V_125C.lib

    instances:

        u_sand_grid_RAM.generate_sram[0].u_sram_a:
          location: [450, 450]
          orientation: N

        u_sand_grid_RAM.generate_sram[1].u_sram_a:
          location: [1000, 450]
          orientation: N

        u_sand_grid_RAM.generate_sram[2].u_sram_a:
          location: [1550, 450]
          orientation: N

        u_sand_grid_RAM.generate_sram[0].u_sram_b:
          location: [450, 950]
          orientation: N

        u_sand_grid_RAM.generate_sram[1].u_sram_b:
          location: [1000, 950]
          orientation: N

        u_sand_grid_RAM.generate_sram[2].u_sram_b:
          location: [1550, 950]
          orientation: N



