DESIGN_NAME: spi_module
VERILOG_FILES:
- src/pos_edge_det.sv
- src/spi_module.sv

USE_SLANG: true

CLOCK_PERIOD: 10
CLOCK_PORT: sys_clock

# 30% because the design is too small.
FP_CORE_UTIL: 30

FP_ASPECT_RATIO: 1.0
PL_TARGET_DENSITY: 0.55