DESIGN_NAME: clock_divider
VERILOG_FILES:
- src/clock_divider.sv

USE_SLANG: true

CLOCK_PERIOD: 10
CLOCK_PORT: clk

# FP_SIZING: absolute

# DIE_AREA: [0, 0, 35, 55]

FP_CORE_UTIL: 55

FP_ASPECT_RATIO: 1.0
PL_TARGET_DENSITY: 0.55